package org.bytefred.ksat.kissat

import org.bytefred.ksat.DimacsCnf
import org.bytefred.ksat.SatResult
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * File-driven shadow test (JVM only) for the Kotlin [Kissat] (core) port.
 *
 * For every `shadow/cnf/<name>.cnf` that has a matching golden trace at
 * `shadow/golden-kissat/<name>.trace` (produced by the instrumented C kissat core,
 * shadow/kissat-c/kissat_trace.cc run with LSTRACE=1), run the Kotlin Kissat with a
 * trace sink and compare, picking the STRONGEST level that holds:
 *
 *   L1 -- full trace equality, line-for-line. Reported per instance when it holds.
 *   L2 -- the event/decision sequence matches (all DECIDE/CONFLICT/RESTART/REDUCE
 *         lines and the decision variables agree), tolerant of any ASSIGN-order
 *         differences that a differently-rounded double score/EMA tie could produce.
 *   L3 -- always enforced: same SAT/UNSAT verdict, and on SAT the returned model
 *         satisfies the CNF.
 *
 * kissat stores its heap scores (`heap.score`), the score increment (`scinc`) and the
 * glue EMAs in `double` (see the C reference). JVM Double is IEEE-754 like C's double,
 * and every score/EMA update in the port is transcribed in the same evaluation order,
 * so L1 is expected to hold on these instances with [ActivityPrecision.FLOAT64] (the
 * default). If it ever degrades to L2 on a given CNF the test still passes (and prints
 * which level held), but a hard L3 failure (wrong verdict or a model that doesn't satisfy
 * the CNF) is always a bug.
 *
 * Golden traces are regenerated by shadow/tools/regen_golden_kissat.sh. The C reference
 * mirrors the Kotlin reduceIntInit / stableInit knobs via LSREDUCEINIT / LSSTABLEINIT, so
 * a shadowed run uses the same defaults on both sides (which they are here).
 */
class ShadowTraceFilesTest {

    private val shadowDir: File? by lazy { locateShadowDir() }

    private fun locateShadowDir(): File? {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            val candidate = File(dir, "shadow")
            if (File(candidate, "cnf").isDirectory && File(candidate, "golden-kissat").isDirectory) {
                return candidate
            }
            dir = dir.parentFile
        }
        return null
    }

    private fun cases(shadow: File): List<Pair<File, File>> {
        val cnfDir = File(shadow, "cnf")
        val goldDir = File(shadow, "golden-kissat")
        return (cnfDir.listFiles { f -> f.name.endsWith(".cnf") }?.sortedBy { it.name } ?: emptyList())
            .mapNotNull { cnf ->
                val gold = File(goldDir, cnf.nameWithoutExtension + ".trace")
                if (gold.isFile) cnf to gold else null
            }
    }

    /** Reduce a full trace to its structural (L2) skeleton: keep DECIDE/CONFLICT/RESTART/
     *  REDUCE/RESULT verbatim, drop ASSIGN lines (whose interleaving is what a float tie can
     *  perturb). This is the event + decision-variable sequence. */
    private fun l2(trace: List<String>): List<String> =
        trace.filter { !it.startsWith("ASSIGN ") }

    private fun runOne(cnfFile: File, goldFile: File): String {
        val cnf = DimacsCnf.parse(cnfFile.readText())
        val expected = goldFile.readLines().filter { it.isNotEmpty() }

        // Default ctor == upstream kissat intervals (reduceint=300, stableinit=1000) and
        // ActivityPrecision.FLOAT64 == C's `double` scores: the byte-for-byte configuration.
        val solver = Kissat(cnf.numVars)
        val trace = ArrayList<String>()
        solver.setTraceSink { trace.add(it) }
        for (clause in cnf.clauses) solver.addClause(clause)
        val result = solver.solve()

        // L3 (always): verdict + model.
        val resultLine = expected.lastOrNull { it.startsWith("RESULT ") }
            ?: fail("[${cnfFile.name}] golden trace has no RESULT line")
        val expectedResult = if (resultLine == "RESULT SAT") SatResult.SAT else SatResult.UNSAT
        assertEquals(expectedResult, result, "[${cnfFile.name}] verdict mismatch (L3)")
        if (result == SatResult.SAT) {
            assertTrue(
                cnf.isSatisfiedBy { v -> solver.valueOf(v) },
                "[${cnfFile.name}] returned model does not satisfy the CNF (L3)",
            )
        }

        // L1 then L2.
        return when {
            trace == expected -> "L1"
            l2(trace) == l2(expected) -> "L2"
            else -> {
                val a = l2(expected); val b = l2(trace)
                val firstDiff = (0 until minOf(a.size, b.size)).firstOrNull { a[it] != b[it] } ?: minOf(a.size, b.size)
                fail(
                    "[${cnfFile.name}] trace diverges even at L2 (event/decision sequence).\n" +
                        "  expected[$firstDiff]=${a.getOrNull(firstDiff)}\n" +
                        "  actual  [$firstDiff]=${b.getOrNull(firstDiff)}\n" +
                        "  expected events=${a.size} actual events=${b.size}",
                )
            }
        }
    }

    @Test
    fun allGoldenTracesMatch() {
        val shadow = shadowDir ?: run {
            println("[shadow-kissat] no shadow/golden-kissat dir; run shadow/tools/regen_golden_kissat.sh -- skipping")
            return
        }
        val cases = cases(shadow)
        if (cases.isEmpty()) {
            println("[shadow-kissat] no golden traces found; run shadow/tools/regen_golden_kissat.sh -- skipping")
            return
        }
        val levels = LinkedHashMap<String, String>()
        for ((cnf, gold) in cases) levels[cnf.name] = runOne(cnf, gold)
        println("[shadow-kissat] per-instance level achieved:")
        for ((name, lvl) in levels) println("  %-26s %s".format(name, lvl))
        val worst = when {
            levels.values.all { it == "L1" } -> "L1 (full trace) on all instances"
            levels.values.any { it == "L1" } -> "mixed L1/L2 (L3 enforced everywhere)"
            else -> "L2 (structural) + L3"
        }
        println("[shadow-kissat] overall: $worst")

        // HARD L1 GATE (regression guard): with FLOAT64 (== C `double`) scores/EMAs the
        // port is byte-for-byte identical to C on every current instance. Enforce that -- a
        // drop to L2 (e.g. a float-rounding or evaluation-order regression that perturbs
        // ASSIGN interleaving, or a heap positional-tie regression) must FAIL, not silently
        // pass. This is what makes the "byte-for-byte / L1" claim actually tested.
        val degraded = levels.filterValues { it != "L1" }.keys
        assertTrue(
            degraded.isEmpty(),
            "L1 regression: these instances dropped below byte-for-byte L1 to L2: $degraded. " +
                "The port must match C exactly with ActivityPrecision.FLOAT64 and the upstream " +
                "reduce/stabilize defaults. Investigate float rounding / heap positional tie-breaks / " +
                "EMA evaluation order before accepting L2.",
        )
    }

    /** Guard that at least one instance actually drives RESTART and REDUCE, so those
     *  hand-translated kissat paths stay trace-covered. Only enforced when golden
     *  traces exist. */
    @Test
    fun restartReducePathsAreCovered() {
        val shadow = shadowDir ?: return
        val cases = cases(shadow)
        if (cases.isEmpty()) return
        var sawRestart = false
        var sawReduce = false
        for ((_, gold) in cases) {
            val lines = gold.readLines()
            if (lines.contains("RESTART")) sawRestart = true
            if (lines.contains("REDUCE")) sawReduce = true
        }
        assertTrue(sawRestart, "no CNF triggers RESTART -- RESTART path not trace-covered. Add a harder instance.")
        assertTrue(sawReduce, "no CNF triggers REDUCE -- REDUCE path not trace-covered. Add a harder instance.")
    }
}
